--------------------------------------------------------
-- Datei erstellt -Montag-Juli-09-2018 
--------------------------------------------------------
--------------------------------------------------------
-- DDL for Table SALES_REPS
--------------------------------------------------------

CREATE TABLE "SALES_REPS" 
( "ID" NUMBER(6,0), 
"NAME" VARCHAR2(25 BYTE), 
"SALARY" NUMBER(8,2), 
"COMMISSION_PCT" NUMBER(2,2)
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
-- DDL for Index SALES_REPS_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "SALES_REPS_PK" ON "SALES_REPS" ("ID") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;
--------------------------------------------------------
-- Constraints for Table SALES_REPS
--------------------------------------------------------

ALTER TABLE "SALES_REPS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "SALES_REPS" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE "SALES_REPS" MODIFY ("SALARY" NOT NULL ENABLE);
ALTER TABLE "SALES_REPS" ADD CONSTRAINT "SALES_REPS_PK" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ENABLE;