 CREATE TABLE "ORA21"."JOB_GRADES"
   (    "GRADE_LEVEL" VARCHAR2(3 BYTE),
    "LOWEST_SAL" NUMBER,
    "HIGHEST_SAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORA21.JOB_GRADES
SET DEFINE OFF;
Insert into ORA21.JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('A','1000','2999');
Insert into ORA21.JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('B','3000','5999');
Insert into ORA21.JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('C','6000','9999');
Insert into ORA21.JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('D','10000','14999');
Insert into ORA21.JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('E','15000','24999');
Insert into ORA21.JOB_GRADES (GRADE_LEVEL,LOWEST_SAL,HIGHEST_SAL) values ('F','25000','40000');